### ISSUE TITLE
Feature Request: Get the compiled code

### ISSUE THREAD

**Issue by aemonge** [joshnuss/mruby-web-irb#11]
Could it be possible to use this to compile some GEMs that have a CLI (console line interface) from ruby to nodeJs. 

Ideally I would install ruby on my machine and use the GEMs without transpiling them. But in this case I'm stucked to use node.js; so I'm trying to find a compiler from ruby to node.js

**Comment by joshnuss** [comment]
If the gem works with mruby it should be possible. See https://github.com/mruby/mgem-list

This project is just an IRB, you want to use https://github.com/xxuejie/webruby to compile a JS bundle.

Hope that helps

**Comment by aemonge** [comment]
ty :)
