### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by pannous** [joshnuss/mruby-web-irb#7]
Blocked loading mixed active content "http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"[Learn More] mruby-web-irb
Blocked loading mixed active content "http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js"[Learn More]
https://developer.mozilla.org/en-US/docs/Security/MixedContent

**Comment by joshnuss** [comment]
@pannous can you try http:// instead of https://

**Comment by pannous** [comment]
thanks that worked
 I can't remember where the broken link came from

**Comment by pannous** [comment]
ah,  automatic redirect to https because of browser plug-in

**Comment by nloveladyallen** [comment]
PR #8 would actually fix this issue, instead of just telling users to go use a less secure version.
