### ISSUE TITLE
Link to ace.js on the website is outdated

### ISSUE THREAD

**Issue by Cyan101** [joshnuss/mruby-web-irb#9]
GET https://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js net::ERR_NAME_NOT_RESOLVED

Error from chrome console on the sample IRB page

**Comment by joshnuss** [comment]
Thanks @Cyan101 for reporting. The issue has now been fixed. Seems the CDN was outdated.

Cheers!
